[package]
name = "sciparse"
publish = false
edition.workspace = true

[dependencies]
thiserror.workspace = true
bitflags.workspace = true
tinyvec.workspace = true

[dev-dependencies]
proptest.workspace = true
proptest-derive.workspace = true

[lints]
workspace = true
